### ISSUE TITLE
Support for Ticwatch C2

### ISSUE THREAD

**Issue by josteinaj** [AsteroidOS/asteroid#106]
I see that Ticwatch E & S is supported. Is Ticwatch C2 also supported?

**Comment by jrtberlin** [comment]
No the C2 is not supported. However, the c2 is not that different and should be a fairly easy to port with access to the watch.

**Comment by MagneFire** [comment]
As mentioned in https://github.com/AsteroidOS/asteroid/pull/173, with support for the Ticwatch C2+ this version (non-plus) should also be supported.
Nightly images shall be available in a day or two :smile:
