### ISSUE TITLE
[bass] hrm no data

### ISSUE THREAD

**Issue by bskyh** [AsteroidOS/asteroid#107]
i installed and started asteroid-hrm,but it shows 0 always.
i noticed that the sensor light flashed once when the system started.

**Comment by xonq** [comment]
I'm getting the same issue.

**Comment by MagneFire** [comment]
The latest nightlies have some fixes for the heart rate sensor.

Can you confirm whether this issue still exists in the latest nightly?

**Comment by xonq** [comment]
Yes, this issue still exists. I do not see any lights like OP

**Comment by Machin-Shin** [comment]
Issue still present in recent nightly. I am seeing the light flash once during boot but not when the HRM app is ran. 

My test_sensors output also looks the same as above. https://pastebin.com/4PYs8GjE
