### ISSUE TITLE
Support for the PineTime

### ISSUE THREAD

**Issue by Atrate** [AsteroidOS/asteroid#112]
PineTime is an upcoming Linux Smartwatch so porting Asteroid OS to it shouldn't take too much time, yet it can yield benefits for this project's coverage.

https://www.pine64.org/pinetime/

**Comment by jrtberlin** [comment]
We would love to support it. Unfortunately, the PineTime is not a Linux smartwatch. It uses FreeRTOS or Mbed. The hardware is under the minimum requirements for Linux.

**Comment by Atrate** [comment]
Oh, didn't realize that, thanks!

**Comment by jrtberlin** [comment]
@Atrate No worries! The watch is currently not listed on our [porting status page](https://asteroidos.org/wiki/porting-status/).
