### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by 0k00l** [AsteroidOS/asteroid#119]
Hi
I tried to build AsteroidOS on Docker but got an error like follows:

`Initialising tasks: 100% |#######################################################################################################################################################################################| Time: 0:00:06
Sstate summary: Wanted 1051 Found 0 Missed 1051 Current 871 (0% match, 45% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: nemo-qml-plugin-contextkit-+gitAUTOINC+4a39923bda-r1 do_fetch: Failed to fetch URL git://git.merproject.org/mer-core-attic/nemo-qml-plugin-contextkit.git;protocol=https, attempting MIRRORS if available
ERROR: nemo-qml-plugin-contextkit-+gitAUTOINC+4a39923bda-r1 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export PATH="/asteroid/src/oe-core/scripts:/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/recipe-sysroot/usr/bin/crossscripts:/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/recipe-sysroot-native/usr/sbin:/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/recipe-sysroot-native/usr/bin:/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/recipe-sysroot-native/sbin:/asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/recipe-sysroot-native/bin:/asteroid/src/oe-core/bitbake/bin:/asteroid/build/tmp-glibc/hosttools"; export HOME="/mnt/md0/home/h3x0r"; LANG=C git -c core.fsyncobjectfiles=0 clone --bare --mirror https://git.merproject.org/mer-core-attic/nemo-qml-plugin-contextkit.git /asteroid/build/downloads/git2/git.merproject.org.mer-core-attic.nemo-qml-plugin-contextkit.git --progress failed with exit code 128, output:
Cloning into bare repository '/asteroid/build/downloads/git2/git.merproject.org.mer-core-attic.nemo-qml-plugin-contextkit.git'...
fatal: could not read Username for 'https://git.sailfishos.org': No such device or address

ERROR: nemo-qml-plugin-contextkit-+gitAUTOINC+4a39923bda-r1 do_fetch: Fetcher failure for URL: 'git://git.merproject.org/mer-core-attic/nemo-qml-plugin-contextkit.git;protocol=https'. Unable to fetch URL from any source.
ERROR: nemo-qml-plugin-contextkit-+gitAUTOINC+4a39923bda-r1 do_fetch: 
ERROR: nemo-qml-plugin-contextkit-+gitAUTOINC+4a39923bda-r1 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /asteroid/build/tmp-glibc/work/armv7vet2hf-neon-oe-linux-gnueabi/nemo-qml-plugin-contextkit/+gitAUTOINC+4a39923bda-r1/temp/log.do_fetch.223
ERROR: Task (/asteroid/src/meta-asteroid/recipes-nemomobile/nemo-qml-plugins/nemo-qml-plugin-contextkit_git.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3300 tasks of which 3294 didn't need to be rerun and 1 failed.`

I think it is not related to build itself bu rather to url change in merproject - but not sure ;)

**Comment by FlorentRevest** [comment]
Thanks for reporting. git pull your meta-asteroid and try again, this should be solved :)
