### ISSUE TITLE
[tetra] bootloop with all nightlies

### ISSUE THREAD

**Issue by Mach3Penguin** [AsteroidOS/asteroid#123]
1.0 is running smoothly on tetra (known issues: no vibration, no haptics). but all nightlies result in bootloop with the smartwatch3 logo since then.

**Comment by Mossfeldt** [comment]
Same issue for me. Boots and runs v1.0 just fine but nightly (1-july) stops at boot.

**Comment by MagneFire** [comment]
FYI this issue is a duplicate of https://github.com/AsteroidOS/asteroid/issues/100. I have added some instructions there if you wish to help solve this issue.
