### ISSUE TITLE
[Bass]Compass inaccurate

### ISSUE THREAD

**Issue by issu-shooter** [AsteroidOS/asteroid#130]
The compass app can not find real north and south, it takes the watch's 12 o'clock direction as north when you opened it.

**Comment by jrtberlin** [comment]
The compass is [listed as supported](https://asteroidos.org/install/bass/). 
Have you tried to calibrate the compass with the typical 8-figure already? 
![8-figure compass calibration](https://lh3.googleusercontent.com/eloZBMBLQ9o8CC_84rfN-JedVCdzStQhhbs1FImcgOEmUYoeijg-tS4xNh6Kmd234n4=w350)

**Comment by issu-shooter** [comment]
oh....So I have to do this calibrating...! Sorry for the disturbance!

**Comment by jrtberlin** [comment]
Did it solve the issue for you?

**Comment by issu-shooter** [comment]
Well, I tried, and it did work. Really nice. Thanks a lot!
