### ISSUE TITLE
Error when building for sturgeon

### ISSUE THREAD

**Issue by pomputer** [AsteroidOS/asteroid#138]
Hi!
[Here](https://gist.github.com/pomputer/acde542b9839af1d71ceb1952f6eab62) is the error I get when running `bitbake asteroid-image`.
I am on ArchLinux.

Thank you!

**Comment by divad42** [comment]
I have the same problem on Debian Sid.

**Comment by divad42** [comment]
incidentally I did not have the problem building using Docker

**Comment by beroset** [comment]
We've been successfully building for some years, so closing this as no longer applicable.
