### ISSUE TITLE
[Build Failure] Multiple issues with building

### ISSUE THREAD

**Issue by Doomsdayrs** [AsteroidOS/asteroid#141]
Initial build via non-docker install:
1. `qemu-native fails at build due to undefined refrence to stime`
Here is the error log [log.do_compile.3688057.txt](https://github.com/AsteroidOS/asteroid/files/5739742/log.do_compile.3688057.txt)

Docker install:
Utilizing this command
```docker rm -f asteroidos-toolchain; docker run --name asteroidos-toolchain -it -v /etc/passwd:/etc/passwd --user 1000:1000 -v "$HOME/.gitconfig:/$HOME/.gitconfig" -v "$(pwd):/asteroid" asteroidos-toolchain bash -c "source ./prepare-build.sh tetra && bitbake asteroid-image -k"```
I got past the stime issue, but now run into the following. 
1. [devtool issue?.txt](https://github.com/AsteroidOS/asteroid/files/5743396/devtool.issue.txt)
This did not occur a second time, but instead spat out the next error

2. [qtscene issue?.txt](https://github.com/AsteroidOS/asteroid/files/5743401/qtscene.issue.txt)
[log.do_compile.258.txt](https://github.com/AsteroidOS/asteroid/files/5743406/log.do_compile.258.txt)

**Comment by MagneFire** [comment]
The issue you describe is identical to this: https://github.com/AsteroidOS/asteroid/pull/122
It looks like the `warrior` Yocto is getting a bit old. The probable solution is to upgrade the entire build system to a new version (`gatesgarth` maybe). Though upgrading will likely introduce some more errors.

The workaround currently is to use the Docker installation method.
I think we will start to upgrade every layer when we publish a new stable release.

**Comment by Doomsdayrs** [comment]
Ima try to replace the refrences before docker. Because it took an eon to sync up with got simply

**Comment by Doomsdayrs** [comment]
nvm about that, but a maintenance release would be optimal for this project

**Comment by Doomsdayrs** [comment]
what the absolute #### is the CLI syntax in https://asteroidos.org/wiki/building-asteroidos/ meant to mean?? 

Even the documentation underneath it is confusing

**Comment by Doomsdayrs** [comment]
it DOESNT EVEN RUN BY COPY PASTE AAAAAAAAAAAAAAAAAAAAAAA

**Comment by Doomsdayrs** [comment]
```sudo docker run --name asteroidos-toolchain -it -v /etc/passwd:/etc/passwd -v "$HOME/.gitconfig:/$HOME/.gitconfig" -v "$(pwd):/asteroid" asteroidos-toolchain bash -c "source ./prepare-build.sh tetra && bitbake asteroid-image"``` Took me way to long to make a command that just WORKS

**Comment by Doomsdayrs** [comment]
Nope that doesnt work either

**Comment by Doomsdayrs** [comment]
Figured it out,

AFTER A TON of annoying digging, you need to run this shit as user and have to add the user to the docker group according to https://docs.docker.com/engine/install/linux-postinstall/

So the command i posted above does it

**Comment by Doomsdayrs** [comment]
So in sum
Do this https://docs.docker.com/engine/install/linux-postinstall/ after installing docker

run this after creating the docker image in user mode
```
docker run --name asteroidos-toolchain -it -v /etc/passwd:/etc/passwd --user 1000:1000 -v "$HOME/.gitconfig:/$HOME/.gitconfig" -v "$(pwd):/asteroid" asteroidos-toolchain bash -c "source ./prepare-build.sh tetra && bitbake asteroid-image -k"
```

It now runs

**Comment by FlorentRevest** [comment]
If what you want is help, please stay patient and cordial.
If what you want is to complain, please stick to professionally supported operating systems.

I certainly don't like docker either and share your frustration but the best way to improve the situation is to contribute updates to the documentation, not scream in a GitHub issue.
Thanks for the time you spent debugging this and merry Christmas. ;)

**Comment by Doomsdayrs** [comment]
Sorry about that, Was a stressful night for me. Anyhows, I'm renaming the issue as "Build Issues on Master". Since I found more then one issue coming up

**Comment by FlorentRevest** [comment]
I understand :) Thank you Doomsdayrs, keep the feedback coming, it's helpful. MagneFire already started to improve the documentation based on your feedback.

**Comment by Doomsdayrs** [comment]
The fixed up documentation is much better now! I would've never thought to add `'`s to the command

**Comment by Doomsdayrs** [comment]
At my [repo](https://github.com/Doomsdayrs/asteroid/tree/docker-script) I started work on a simple bash script which would install docker and execute it with inputted params. For ease sake

**Comment by Doomsdayrs** [comment]
Completed work on it, What do you all think?

**Comment by Doomsdayrs** [comment]
Tried out building `gatesgarth`, Here is the latest issue I have
```
ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Your Python 3 is not a full install. Please install the module distutils.sysconfig (see the Getting Started guide for further information).
```

**Comment by MagneFire** [comment]
The reason for all the updates to gatesgarth was to remove the need for Docker now :smile:

But we should now also update the Dockerfile so that it works with the updated files. Someone worked on this a while back (https://github.com/AsteroidOS/asteroid/pull/122).

I should point out that you will get build errors when you have Python 3.9 installed. You may have to that downgrade to Python 3.8.x. We are waiting for upstream OpenEmbedded to update `xcbproto` to fix this. (https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-graphics/xorg-proto/xcb-proto_1.14.1.bb isn't part of `gatesgarth` yet.)

**Comment by Doomsdayrs** [comment]
Building is finally fixed for me

**Comment by Doomsdayrs** [comment]
Well, I assume its for others too since it built just fine with the latest commit as of this message
