### ISSUE TITLE
Support for Bakeey os / i9 (Huawei gt2 clone)

### ISSUE THREAD

**Issue by Exoteric28** [AsteroidOS/asteroid#144]
Title. Willing to do work if I can.

Here's the board / processor in mine: HS6620

https://amp.reddit.com/r/AskElectronics/comments/e1fbrz/any_info_on_the_chip_labeled_hs6620_found_in/

**Comment by jrtberlin** [comment]
It has less than [128 MB ROM](https://de.aliexpress.com/i/1005001392018217.html) and the [HS6620](https://ae01.alicdn.com/kf/H0dd379b47d724197895348596de5c4637.jpg) seems to be a [Cortex M3 based microcontroller with 384 KB RAM](http://www.onmicro.com.cn/portal/article/index/cid/40/id/231.html).

The watch does not meet the minimum requirements to run a full Linux kernel + userland.
