### ISSUE TITLE
Question: Apps

### ISSUE THREAD

**Issue by JMans15** [AsteroidOS/asteroid#185]
There's a section in the documentation about installing packages and another about creating apps, are these "packages" "apps", are there apps available somewhere? I can't find any on google

**Comment by jrtberlin** [comment]
There is no comprehensive list. 
- Some apps are in our repository: https://release.asteroidos.org/nightlies/ipk/armv7vehf-neon/ 
- Asteroid Top: https://github.com/aebruno/asteroid-top
- Asteroid Authenticator: https://github.com/ChandlerSwift/asteroid-authenticator

There are probably a few more that I'm not aware of, but there isn't a huge app ecosystem.
