### ISSUE TITLE
[Feature Request] Add documentation for qml-asteroid

### ISSUE THREAD

**Issue by dodoradio** [AsteroidOS/asteroid#231]
**Is your feature request related to a problem? Please describe.**
qml-asteroid is currently only documented in a few places in the source code. it would be ideal if we could get a documentation page for this, with clear descriptions of all the properties that can be set for each item

**Describe the feature you'd like**
I'm not sure if this should be on the website, or a text or html file in the qml-asteroid repo, some more opinions are needed

thanks to tydragon for raising this issue

**Comment by beroset** [comment]
A first step for this is now merged: https://github.com/AsteroidOS/qml-asteroid/pull/38

**Comment by beroset** [comment]
Done.
