### ISSUE TITLE
Finished build is tiny (less than 100 bytes)

### ISSUE THREAD

**Issue by RAZERZ** [AsteroidOS/asteroid#26]
So the build finally compiled (after a couple of hours) but the end result is tiny!
I built for the sony smartwatch 3 (tetra) and I got the files that where available for download (except the one I made was ext4 instead of ext2) but the files on the website are around 300+ megabytes, while the ones I got in the end where tiny! Are they supposed to be like that? Thanks.

**Comment by RAZERZ** [comment]
Update: I think I was talking about the wrong files... The ones I got had the same names etc but I found other files that were larger, they're rootfs though.

**Comment by FlorentRevest** [comment]
The tiny files with short names are symbolic links to the larger files with names including build date. This is not a bug

**Comment by RAZERZ** [comment]
Running "ls -al" confirmed this

1336117 RAZERZ SK488

Le 21 mai 2017 12:07 PM, "Florent Revest" <notifications@github.com> a
écrit :
