### ISSUE TITLE
[qemux86] Emulator version of the SDK is not being built

### ISSUE THREAD

**Issue by beroset** [AsteroidOS/asteroid#269]
**Describe the bug**
The qemux86 version of the SDK (which should be here: https://release.asteroidos.org/nightlies/sdk/oecore-x86_64-core2-32-toolchain-nodistro.0.sh ) is missing.

**To reproduce**
1. Go to https://release.asteroidos.org/nightlies/qemux86/
2. Observe that the directory is empty

**Expected behavior**
As documented in our [instructions](https://wiki.asteroidos.org/index.php/Emulator#Get_a_qemux86_build_of_AsteroidOS), to build for the emulator requires installing the emulator version of the SDK.  C

**Device (please complete the following information):**
 - Watch Codename: qemux86

**Additional context**
Add any other context about the problem, e.g.
- This once worked, so there may have been a build script regression.

**Comment by MagneFire** [comment]
The SDK is back again: https://release.asteroidos.org/nightlies/sdk/oecore-x86_64-armv7vehf-neon-toolchain-nodistro.0.sh
