### ISSUE TITLE
I can not select wallpaper or watchfaces 

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid#27]
I'm having trouble choosing a wallpaper or watchface  in current dev-build  > D O  R Y

**Comment by FlorentRevest** [comment]
Problem already fixed by https://github.com/AsteroidOS/meta-asteroid/commit/7b4cdeef844e26c5b51ad35ba0b9add203af609c
This commit was pushed slightly later than the nightly build.
