### ISSUE TITLE
[Feature Request] Complications

### ISSUE THREAD

**Issue by lockSmxth5x** [AsteroidOS/asteroid#271]
Salutations,

I often find it frustrating when I want to change the location of complications on the watch face in Asteroid OS, only to realize two things: First, there aren't many apps to use complications with, and second (the more on-topic and important one), you can't edit them.

Enabling users to customize complications would bridge the gap between Asteroid OS and other smartwatch operating systems, such as Wear OS and watchOS. In these competing platforms, users enjoy the convenience of readily available complication customization options. Implementing this feature in Asteroid OS would align the user experience more closely with what's expected in the smartwatch market and enhance its overall usability.

Thank you and Best Regards,
LockSmxth5x

**Comment by beroset** [comment]
Thanks for your interest, but this issue has already been created.  Please feel free to add detail there.

Duplicate issue:  https://github.com/AsteroidOS/asteroid/issues/136
