### ISSUE TITLE
Dory stay freeze in reboot 

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid#28]
In current dev-build a issue is in reboting. After flash i need select my idiom(es) to get my idiom the watch need reboot, that's where it stays freeze.

**Comment by FlorentRevest** [comment]
I don't understand your bug description.

Also please join logs to your bug report by booting into debug mode with:
fastboot boot zImage-dtb-****.fastboot -c debug-ramdisk
and then follow the instructions at the bottom of https://asteroidos.org/wiki/boot-process/ and paste the results of journalctl somewhere

**Comment by Caballlero** [comment]
Just reporting that this issue look like fixed in dev-buil-04-Jun-2017...
