### ISSUE TITLE
Translation are not shipped in setting app..

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid#30]
A ugly bug being from the last 2 dev-buils. Translation are not showed in settings/app

**Comment by Caballlero** [comment]
Hello: Florent
Any news about of this?
Thanks . . .

**Comment by FlorentRevest** [comment]
I still haven't had the time to look at it...

**Comment by Caballlero** [comment]
ok thank you.

**Comment by FlorentRevest** [comment]
Fixed by https://github.com/AsteroidOS/qml-asteroid/compare/1e8d754f0f9b...d015aede8542

Thanks for reporting!
