### ISSUE TITLE
Feature Request: 12-hour format clock

### ISSUE THREAD

**Issue by Espionage724** [AsteroidOS/asteroid#32]
Just a minor request. My smartwatch currently doesn't really do much but tell time, and I would like to just use AsteroidOS instead of Android Wear. I'm used to a 12-hour clock format however.

Alternatively, perhaps a watch face that has both 24-hour and 12-hour time would be nice.

**Comment by FlorentRevest** [comment]
Hi Espionage724,

This problem should have been solved by https://github.com/AsteroidOS/asteroid-settings/commit/3885e1518038951728ba24fe0ab766d666c21b81 and a series of patches in asteroid-launcher, alarmclock, calendar etc... Small problems may still be hidden here and there so testing is welcome!

Thanks for your interest!
