### ISSUE TITLE
asteroid-image-dory.ext4 boot issue 

### ISSUE THREAD

**Issue by InfinitelyManic** [AsteroidOS/asteroid#33]
https://release.asteroidos.org/nightlies/dory/asteroid-image-dory.ext4 will NOT boot using https://release.asteroidos.org/nightlies/dory/zImage-dtb-dory.fastboot

But:
https://release.asteroidos.org/nightlies/dory/asteroid-image-dory.ext4 BOOTS up using https://asteroidos.org/wp-content/uploads/releases/1.0-alpha/zImage-dtb-dory.fastboot 

Menus and button selections ARE WORKING!

**Comment by FlorentRevest** [comment]
The problem is not the image but the flash instructions that were incorrect. The new website makes it much clearer how to flash nightlies https://asteroidos.org/install/
