### ISSUE TITLE
Asteroid OS not boot after choosing language on a fresh flash 

### ISSUE THREAD

**Issue by Caballlero** [AsteroidOS/asteroid#35]
After flash then choosing language the watch need reboot to make effect the language then most time not boot as well.

**Comment by Caballlero** [comment]
Hi 
Any info of this?

**Comment by FlorentRevest** [comment]
No update on this. This is most likely a corrupted partition which seems to happen quite often now for no apparent reason. That would need further debugging from the ramdisk but I can not reproduce the issue myself and I don't think I can tele-guide you through the debugging of this...

**Comment by Caballlero** [comment]
Ok. What would be a simple solution on this?

**Comment by FlorentRevest** [comment]
Not all the problems have simple solutions!

**Comment by Caballlero** [comment]
:  )  Is this caused by making  many flash on the watch?

**Comment by FlorentRevest** [comment]
It can be one of the cause. Also, do you force your watch to shutdown by holding the power button for a while when you reboot after selecting a new language? Because this can lead to fs inconsistencies. Fsck is ran at each boot in order to fix this kind of problems but sometimes the fs is in such a bad state that it can't be fixed.

**Comment by Caballlero** [comment]
I do some time, but apparently only happens when i select a language, because after flash the clock, the clock turns on well. The problem is choosing a language which the clock needs to restart to take effect, where it is locked with white screen . . .

**Comment by Caballlero** [comment]
Also i am compiling the source(AndroidSinc) ,but i get this error . . .
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:

**Comment by Caballlero** [comment]
I fixed this 
Fix the issues identified by lint, or add the following to your build script to proceed with errors:
...
android {
lintOptions {
abortOnError false
}

**Comment by Caballlero** [comment]
I flashed today my watch , it is look like fixed this issue.
