### ISSUE TITLE
Return to Android Wear

### ISSUE THREAD

**Issue by croccio** [AsteroidOS/asteroid#4]
I have a Samsung Gear Live. I want try to port asteroid os to it, but if i want return to Android Wear is it possible?

**Comment by FlorentRevest** [comment]
Yes sure ! 
Actually,  if you boot your kernel using fastboot and mount your rootfs in loop you won't even replace your android wear installation so it will be ok. 
If you  need any help on porting you can come on IRC.

**Comment by croccio** [comment]
Yes sir! i'll come on IRC :)
