### ISSUE TITLE
[Smartwatch 3/tetra] Doesn't build

### ISSUE THREAD

**Issue by gmelchett** [AsteroidOS/asteroid#44]
Started a fresh build last night 4th November, (newly installed xubuntu 16.04 in a virtual box, since building on Arch Linux doesn't work) and this morning I saw that the build has failed:
```
mv: cannot stat '/home/jonas/asteroid/build/tmp-glibc/work/armv7vehf-neon-oe-linux-gnueabi/libsignon-qt5/+gitAUTOINC+440587278e-r1/image/usr/lib64/': No such file or directory
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_install
```
Attaching log of an attempted rebuild. (mkdir -p the missing directory doesn't help)

[log.do_install.3458.gz](https://github.com/AsteroidOS/asteroid/files/1443072/log.do_install.3458.gz)

**Comment by FlorentRevest** [comment]
Thanks for reporting gmelchett.
