### ISSUE TITLE
dory: vibration no longer works

### ISSUE THREAD

**Issue by craftyguy** [AsteroidOS/asteroid#56]
I seem to recall vibration working on dory a few months back when I last tested asteroidos on my watch, but after installing the latest nightly (as of yesterday), it no longer works.

I can confirm this by running `test_vibrator` on the device, and nothing happening.

**Comment by craftyguy** [comment]
It seems that it *does* work, it's just disabled by default. I don't know if this is intended or not. If it is, feel free to close this issue but having some note to users that it is disabled by default might be helpful!

**Comment by FlorentRevest** [comment]
They should actually be enabled by default. I'll give it a look.
However, test_vibrator is not supposed to work on dory.

**Comment by FlorentRevest** [comment]
I suspect this https://github.com/AsteroidOS/meta-asteroid/commit/610307e9cad40b1871d55cf171dae603208a7d75 could have been the source of your issue.
Could you please try the next nightly (when it will be built, in a couple of days) and tell me if your problem is fixed?

**Comment by craftyguy** [comment]
Sure! Would it be possible to get this fix with a 'opkg upgrade' on an existing install of asteriodos?

**Comment by FlorentRevest** [comment]
That fix should be included in an opkg upgrade indeed.

**Comment by craftyguy** [comment]
It seems to work now, thanks!
