### ISSUE TITLE
Add support for heart rate sensors

### ISSUE THREAD

**Issue by SZenglein** [AsteroidOS/asteroid#60]
It would be cool if there was high level support for heart rate sensors.

**Comment by PeterGamma** [comment]
Me too. If a progammer has fun to Port the Adafruit Open Source Bike computer to Asteroid OS, that would be great:

https://petergamma.org/read-out-sensor-data-from-the-adafruit-clue-pyloton/

then, whe had an AsteroidOS sports watch which can compete with a Garmin watch.

**Comment by eLtMosen** [comment]
https://github.com/AsteroidOS/asteroid-hrm
