### ISSUE TITLE
ASUS Zenwatch 1 (anthias) - Touch screen and power consumption

### ISSUE THREAD

**Issue by druk13** [AsteroidOS/asteroid#73]
There are strange touch screen and power consumption problems:

1) If the watch is loading in the cradle, the touch screen is usable also when bluetooth is on. If you take out the watch from the cradle with bluetooth on and the watch enters the first time in “power-save mode (?)”, the touch screen is not usable anymore.

2) If you power on the watch and bluetooth is on, the touch screen is not usable after the first time entering “power-save mode (?)”. Immediately disabling bluetooth after power on the watch can work but must not.

3) The power consumption is so huge, that my watch with a new battery is empty after 6 hours.

With this touch screen and power consumption issue the watch is only a watch with a screen on button on the bottom of the watch and not really usable and usefull.

**Comment by FlorentRevest** [comment]
Hi @druk13, thanks for reporting but the bug you mention is already tracked under the anthias repository https://github.com/AsteroidOS/meta-anthias-hybris/issues/1 (the anthias install page has a warning pointing to that issue)
This only affects anthias so I'll close this issue. If you think you have additional details worth mentioning, feel free to comment on the other issue.
