### ISSUE TITLE
KingWear - KW18 support

### ISSUE THREAD

**Issue by GiovanniSM20** [AsteroidOS/asteroid#74]
I gained this watch but hated the system and wondered if I could test the AsteroidOS in it.

I can't find the option to unlock the bootloader.

**Comment by parkerlreed** [comment]
It does not appear to be Android based. There is most likely no way to port to that device.

**Comment by FlorentRevest** [comment]
Indeed, I'm afraid @parkerlreed is right, there is no way to port AsteroidOS to that device.
I'll close this issue as it can not progress any further.
