### ISSUE TITLE
Ambient display on wrist motion

### ISSUE THREAD

**Issue by Shadow53** [AsteroidOS/asteroid#82]
My Moto 360 watch with Android Wear supported peeking an ambient display for a few seconds if it detected the motion of me lifting my wrist to look at the screen. I've since switched to an LG G Watch running AsteroidOS and the lack of this feature is the biggest pain point, since I have to gesture on the screen a bit before it turns on. If there's something in my other hand, there's a hassle of setting down the thing or awkwardly rubbing the screen with my nose, just to look at the time.

I figure a combination of input from the accelerometer and/or the gyroscope would give the necessary information to determine the user is looking at their watch. I can collect some example data from own watch, if that will help any; I would just need some direction on how to do that.

**Comment by njfox** [comment]
> Every WearOS watch comes with a device that can wake up the watch when a movement is detected. On dory, it is the lis3dsh.

Do you know offhand what device it is in bass?

**Comment by FlorentRevest** [comment]
No, but maybe you can find that using test_sensors

**Comment by jrtberlin** [comment]
We have support for [tilt-to-wake](https://github.com/AsteroidOS/mce/pull/6) and [allways-on](https://github.com/AsteroidOS/meta-asteroid/pull/43) now.
