### ISSUE TITLE
[bass] Battery indicator showing "undefined%"

### ISSUE THREAD

**Issue by CharlesCage** [AsteroidOS/asteroid#95]
v1.0 / bass

New install, first flash. Battery indicator shows empty with "undefined%"

Charge before reflash was 70%

Tried restart as well.

**Comment by JNissi** [comment]
Duplicate of #94 with different hardware, so the problem is probably in meta-asteroid. (?)

**Comment by FlorentRevest** [comment]
The problem is most likely in meta-asteroid indeed.
@CharlesCage I'd redirect you to my answer in #94 for now https://github.com/AsteroidOS/asteroid/issues/94#issuecomment-536114052

**Comment by MagneFire** [comment]
Since https://github.com/AsteroidOS/meta-asteroid/pull/83 has been merged. So this issue is finally solved :tada:
